changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: "Breaking Changes"
      labels:
        - breaking
    - title: "New Features"
      labels:
        - enhancement
        - feature
    - title: "Bug Fixes"
      labels:
        - bug
    - title: "Performance"
      labels:
        - performance
    - title: "Documentation"
      labels:
        - documentation
    - title: "House Keeping"
      labels:
        - chore
        - dependencies
    - title: "Other Changes"
      labels:
        - "*"
